/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddFarmLogRequest {
  'crop' : string,
  'date' : string,
  'note' : string,
}
export interface Crop {
  'watering' : string,
  'name' : string,
  'description' : string,
  'season' : string,
  'spacing' : string,
  'daysToHarvest' : bigint,
}
export interface FarmLog { 'crop' : string, 'date' : string, 'note' : string }
export interface Pest {
  'name' : string,
  'treatment' : string,
  'affectedCrops' : string,
  'symptoms' : string,
}
export interface Profile { 'farmName' : string, 'location' : string }
export interface Question { 'question' : string, 'answer' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFarmLog' : ActorMethod<[AddFarmLogRequest], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCrops' : ActorMethod<[], Array<Crop>>,
  'getAllPests' : ActorMethod<[], Array<Pest>>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getCallerProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyFarmLogs' : ActorMethod<[], Array<FarmLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerProfile' : ActorMethod<[Profile], undefined>,
  'searchCrops' : ActorMethod<[string], Array<Crop>>,
  'searchPests' : ActorMethod<[string], Array<Pest>>,
  'searchQuestions' : ActorMethod<[string], Array<Question>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];