/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddFarmLogRequest = IDL.Record({
  'crop' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Crop = IDL.Record({
  'watering' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'season' : IDL.Text,
  'spacing' : IDL.Text,
  'daysToHarvest' : IDL.Nat,
});
export const Pest = IDL.Record({
  'name' : IDL.Text,
  'treatment' : IDL.Text,
  'affectedCrops' : IDL.Text,
  'symptoms' : IDL.Text,
});
export const Question = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const Profile = IDL.Record({
  'farmName' : IDL.Text,
  'location' : IDL.Text,
});
export const FarmLog = IDL.Record({
  'crop' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFarmLog' : IDL.Func([AddFarmLogRequest], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
  'getAllPests' : IDL.Func([], [IDL.Vec(Pest)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyFarmLogs' : IDL.Func([], [IDL.Vec(FarmLog)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerProfile' : IDL.Func([Profile], [], []),
  'searchCrops' : IDL.Func([IDL.Text], [IDL.Vec(Crop)], ['query']),
  'searchPests' : IDL.Func([IDL.Text], [IDL.Vec(Pest)], ['query']),
  'searchQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddFarmLogRequest = IDL.Record({
    'crop' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Crop = IDL.Record({
    'watering' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'season' : IDL.Text,
    'spacing' : IDL.Text,
    'daysToHarvest' : IDL.Nat,
  });
  const Pest = IDL.Record({
    'name' : IDL.Text,
    'treatment' : IDL.Text,
    'affectedCrops' : IDL.Text,
    'symptoms' : IDL.Text,
  });
  const Question = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const Profile = IDL.Record({ 'farmName' : IDL.Text, 'location' : IDL.Text });
  const FarmLog = IDL.Record({
    'crop' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFarmLog' : IDL.Func([AddFarmLogRequest], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
    'getAllPests' : IDL.Func([], [IDL.Vec(Pest)], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyFarmLogs' : IDL.Func([], [IDL.Vec(FarmLog)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerProfile' : IDL.Func([Profile], [], []),
    'searchCrops' : IDL.Func([IDL.Text], [IDL.Vec(Crop)], ['query']),
    'searchPests' : IDL.Func([IDL.Text], [IDL.Vec(Pest)], ['query']),
    'searchQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };